package com.idootech.aquarium

class FactsList {

    val mainActivity2 = MainActivity2()

    var mTitle = arrayOf(
        "Angelfish mate for life",
        "Lobsters pee out of their face and they pee on each other to communicate",
        "Spider crabs are the masters of disguise",
        "The digestive system of sea cucumbers cleans the ocean",
        "Mating leaves male octopi confused for life",
        "Beaches are actually made of parrotfish droppings",
        "Flatfish are born like normal fish:",
        "Seahorse males carry babies and give birth",
        "A blue whale’s tongue is heavier than an elephant",
        "Shark teeth can grow back for their entire life",
        "Scorpionfish eggs only take two days to hatch",
        "Frogfish can walk",
        "A ghost pipefish’s head makes up almost half of its body",
        "Eating puffer fish can kill you",
        "Stonefish are one of the most dangerous sea animals",
        "Dolphins enjoy getting high",
        "Crab’s have tastebuds on their feet:",
        "Blennies are one of the few aquatic species that can survive on land:",
        "Shrimp are the nice guys of the ocean",
        "Lobster can re-grow an eye or an arm",
        "Octopuses are the most caring mums in the world! ",
        "Only Prisoners used to eat lobsters",
        "Seahorses are quite special",
        "Dolphins are sleepwalkers",
        "Parrot fish use snort pillows",
        "You would rather lose a leg than be stung by a Stone fish",
        "Sharks aren’t as bad as they seem",
        "Mantis shrimps are super heroes",
        "When they hatch, baby octopuses are smaller than your pinky finger",
        "Harlequin shrimps have even seen feeding their hostage",
        "Many bony fish have more than just one set of nostrils.",
        "Not all Hermit Crabs use discarded seashells as their portable shelters.",
        "Sharks are covered with tiny little teeth called dermal denticles.",
        "Greenland sharks can live for over 400 years!",
        "Dolphins have ‘X-ray vision’",
        "Corals can be used to replace human bone",
        "Sperm whales have the biggest nose in the animal kingdom",
        "Starfish can be born square",
        "World’s longest pregnancy happens in sharks",
        "Size matters for rainbow octopuses",
        "Size doesn’t matter to harlequin shrimps",
        "Pufferfish create elaborate nests",
        "Sea turtles ‘cry’ salt",
        "Baby sharks eat each other",
        "Lobsters pee on their partners",
        "Iguanas have trident-shape teeth",
        "Little skates can regrow their cartilage",
        "Barnacles can act as whale GPS",
        "The mantis shrimp has the most powerful punch in the animal kingdom.",
        "Sea sponges are older than the dinosaurs",
        "The deepest recorded fish is a ghost",
        "Longest mammal migration occurs in whales",
        "An Octopus has three hearts and the color of its blood is blue.",
        "Seaweeds can be really useful",
        "Some crabs wear living boxing gloves",
        "Dolphins have accents and dialects",
        "Over 60% of octopus cognition happens in their arms",
        "An Electric eel can produce sufficient electricity to light up three bulbs."
    )
    var mDescription = arrayOf(
        "When angelfish choose a partner, it’s for life! If one of them dies, the other one won’t breed with any other mate in their entire lifetime.",
        "The urine nozzles located under their eyes allow lobster to communicate. Peeing on another lobster sends messages necessary for survival.",
        "To survive, spider crabs use sponges, seaweed, and anything that will let them blend in, as camouflage that they stick to their carapace.",
        "Sea cucumbers’ diet consists of anything that sticks to sand at the bottom of the ocean. After they have gotten food out, they poop the sand out clean and tidy.",
        "When a male octopus mates with a female he experiences chronic memory loss known as dementia, so he forever after swims around with no ability to remember.",
        "You know that soft, white sand in tropical islands that you dream about whenever you’re planning your winter vacation? It’s what parrotfish poop after eating coral.",
        "All flatfish babies are born upright like other fishes. As they grow, however, they begin to gradually flatten.",
        "Seahorses are the only animals on earth that aren’t birthed by the mothers. In this unique species it is males who get pregnant.",
        "As the largest animal on earth, the full-grown blue whale is so heavy, just its tongue can weigh more than an entire elephant- that means that it can be heavier than 7,000 kilograms!",
        "Shark teeth are not really teeth, but scales. Because of this, if they ever lose a tooth, it will just grow back",
        "Most animals endure painfully long pregnancies but female scorpionfish don’t waste time. They simply release the eggs into the water to be fertilized by the males, and hatched within two days.",
        "Their pectoral fins are unique and can work as legs that these fishes sometimes use to walk along the sand. When you’re scuba diving, don’t be surprised to see these critters strolling along casually!",
        "This unique fish is incredibly difficult to spot. Once you see it, however, its huge head will surprise you, as it makes up 44% of its entire body!",
        "Poison only resides in part of the puffer fish’ body, which means that it is not only edible, but also delicious. Be careful, though! If the chef doesn’t cut the fish in exactly the right way, this delicacy will be lethal.",
        "Though not on the list of fearsome predators, the poison stonefish carry is the most lethal one in the entire ocean. Combine this with their incredible ability to camouflage and you understand why they are to be feared.",
        "Like many animals, dolphins find natural ways to get high. They use pufferfish to get this effect, and sometimes even do it in groups",
        "Forget about putting food in your mouth! Crab don’t waste time on formalities and just use their feet to taste food.",
        "These slimy fishes have been blessed by evolution, as they can survive outside the water as long as they are damp.",
        "Some species of shrimp have symbiotic relationships with fish and corals. They clean parasites off fish’s mouth, and protect corals in exchange for food.",
        "Just like the lizards or sea-stars, a lobster can regrow an eye or a claw it lost in the mouth of a predator! But the new one will be smaller than the first. ",
        "Once mummy octopus has laid its eggs, it cares for it until they hatch never living their sight, not even to feed! It is believed that mummy octopuses reach their limit as die as soon as their babies are swimming off. When they hatch, baby octopuses are smaller than your fingertip and fully functional.",
        "In the past lobsters were considered at the bottom of the food chain as cockroaches of the sea and were used as bait or fed to prisoners.",
        "Seahorse have no teeth and no stomach, still they are one of the most vicious predators existing, their sneaky hunting technics give them a 90% killing rate. They are the only fish with a neck and a prehensile tail they can use to grab on the anything, grass, coral, or mating partners… they are performing courtship dance for a week before mating. They are master of disguise and can change the shape and color of their skin to blend in their environment.",
        "Dolphins only sleep with half their brain and one eye closed at a time!",
        "During night dive it is common to see a parrot fish sleeping in a crack but have you ever seen the bubble they create around their head made out of their own snort?",
        "While less poisonous than king cobra, stone fish can still be deadly and is apparently the most painful sting human can ever feel. People stung by stonefish usually as doctors to amputate the limb that have been stung in order to stop the pain.",
        "On average, Sharks kills less than 20 people per year. People kill 11,500 sharks per hour. Who's to fear?",
        "If your arms could be as fast as those of a mantis shrimp, you could send a ball to the moon in a throw. Easy! It is believed that the blow from a smashing mantis shrimp is as fast as a 22-caliber bullet. So fast the water is boiling at contact creating a shockwave able to kill its prey even if it manages to avoid the impact.",
        "When first born, an octopus is only about the size of a pea. Right now, we have octopuses ranging from 3 months, at the size of a quarter, to a week and the size of a fingernail.",
        "Harlequin Shrimps feed on sea stars, once they found one (which can be 100 times their size), they turn it over so it cannot run away and eat it slowly. They have even seen feeding their hostage to keep them alive longer!!! ",
        "The nostrils of fish also do not open into the back of the mouth like those of mammals, and are not, therefore, for breathing. They lead into organs of smell, which are very sensitive in order for fish to detect the presence of food in the water at considerable distances. More nostrils = more smelling!",
        "In the Sea of Cortez some hermit crabs use living, growing Hydrocoral and others, in the Indo-Pacific region, live in the fixed wormholes left by marine worms.",
        "Great White Sharks are stealthy hunters and the secret is in their skin. Shark skin is covered by tiny flat V-shaped scales, called dermal denticles, that are more like teeth than fish scales. These denticles decrease drag and turbulence, allowing the shark to swim faster and more quietly.",
        "This means there are Greenland sharks currently swimming around the arctic that were born in the 1600’s. Researchers discovered this by looking at the levels of radioactivity in the growth rings of their eye lenses caused by cold war nuclear bomb tests.",
        "Dolphins can technically see-through other animals! The high-pitched sound they produce for echolocation only rebounds of hard surface such as bone and cartilage, but passes through soft tissue. This allows them to see (or more accurately, hear) through other animals.",
        "The chemical composition and structure of some corals is so similar to our own bones, that they can actually be used in bone grafts! Some alterations have to be made to the coral before insertion, but it is actually beneficial for the patients who require less surgery",
        "Sperm whales use their enormous snouts to create loud booming noises in the deep ocean, by reverberating sound waves in a large ‘drum’ in their noses. This is likely used for communication in the pitch black waters they hunt in.",
        "Some starfish suffer from an extremely rare birth defect and are actually square in shape! It can only happen to sea stars with five points and the exact nature of the mutation is still unknown.",
        "Frilled sharks have the longest gestation period of any vertebrate, capable of pregnancies as long as three and a half years (that’s 42 months!) and if that wasn’t bad enough the litter size can be as big as 15 offspring.",
        "The blanket octopus (aka the rainbow octopus) have one the most extreme cases of sexual dimorphism (where different sexes are sized or shaped differently) in the animal kingdom. Whereas females grow to six feet in length, males only grow to be an inch long!",
        "Harlequin shrimps feed on starfish up to 10x their size by flipping them over so they cannot escape. They will then feed on them throughout the next few days whilst they are still alive!",
        "Male white-stripped pufferfish create one of the most intricate nests found anywhere on Earth. They create these beautiful mandala circles using only their anal fin and once they’ve attracted a female to mate with, they will guard the eggs in the centre of it.",
        "Sea turtles cannot process all of the salt from the seawater they drink in their kidneys. Therefore they secrete excess salt through a gland below their eyes, often giving the impression they are crying when on land.",
        "The embryos of sand tiger sharks will eat their siblings inside their mother’s uterus. It is known as embryonic cannibalism and whilst a mother may start with 10 embryos (which can also belong to different dads) she will only ever give birth to a max of two.",
        "The complex courtship behaviour between most lobster species actually involves urinating on each other. Lobsters can mix powerful pheromones into their urine which they use to communicate and also control one another’s behaviour.",
        "Marine iguanas have trident-shaped teeth that are specially designed for scraping algae off rocks. It gives them the appearance of little hands that wave at you from their gaping smiles.",
        "Little skates are the only known organism that are able to regrow and repair their own cartilage skeletons. This discovery has led to trials to see if the same technique can be used to do the same in humans.",
        "The oxygen isotopes of barnacle shells can be used to track the migration routes of the whales they are attached to. In fact, even fossilized barnacles can be used to do this for whales that lived millions of years ago!",
        "The mantis shrimp has the most powerful punch in the animal kingdom. They can strike their claws at 50mph with the equivalent force of a .22 calibre bullet and can even create sparks underwater!",
        "Sea sponges were around more than 640 million years ago. Experts believe they are closely related to the very first multi-cellular organism. They can also live for over 11,000 years, making them the most long-lived animals ever!",
        "The deepest living fish ever recorded is the ghost fish, filmed during a dive into the Mariana Trench at a depth of 8,143m!",
        "The longest known mammal migration was achieved by a gray whale travelling 22,511km over the course of 172 days!",
        "Octopuses actually have 3 hearts, a systemic heart which pumps blood around the body and 2 branchial hearts that pump it through their gills. If that wasn’t weird enough their blood is also blue, because it contains copper instead of iron.",
        "Special compounds extracted for the cell walls of brown algae, known as alginates, are used widely in everyday products including beer, ice cream, adhesives, ceramics, paper, explosives, waterproof fabrics and antacids, as well as being trialled in bone and brain tissue regeneration experiments.",
        "Boxer crabs use anemones as ‘boxing gloves’ to fight off predators. In this form of symbiosis the anemones get free travel and food in return for being used as a stinging weapon to protect its crustacean host.",
        "Researchers have shown that distinct groups of dolphins from the same species show variation in the sounds they make to communicate. This is one of the strongest pieces of evidence that these cetaceans have actually developed a language which is passed down through generations.",
        "Unlike most other animals, octopus neural networks actually extend out of their centralized brain and into their arms. This means each arm has its own ‘separate’ brain and can act individually from the rest of the body, this is what allows them to have such incredible control over their arms and individual suckers. Because they can re-grow detached arms, this also means they have the ability to re-grow brain tissue.",
        "The electric eel gets its name from its shocking abilities! Special organs in the eel’s body release powerful electric charges of up to 650 volts—that’s more than five times the power of a standard wall socket.\n" +
                "Electric eels are nocturnal, live in muddy, dark waters, and have poor eyesight. So instead of using eyes, electric eels emit a weak electric signal, which they use like radar to navigate, to find a mate, and to find prey. Once prey is found, electric eels will use a much stronger shock to stun prey, usually smaller fish.\n"
    )

    var images = intArrayOf(
        R.drawable.facts_one,
        R.drawable.facts_two,
        R.drawable.facts_three,
        R.drawable.facts_four,
        R.drawable.facts_five,
        R.drawable.facts_six,
        R.drawable.facts_seven,
        R.drawable.facts_eight,
        R.drawable.facts_nine,
        R.drawable.facts_ten,
        R.drawable.facts_eleven,
        R.drawable.facts_twelve,
        R.drawable.facts_thirteen,
        R.drawable.facts_fourteen,
        R.drawable.facts_fifteen,
        R.drawable.facts_sixteen,
        R.drawable.facts_seventeen,
        R.drawable.facts_eighteen,
        R.drawable.facts_nineteen,
        R.drawable.facts_tweenty,
        R.drawable.facts_tweenty_one,
        R.drawable.facts_tweenty_two,
        R.drawable.facts_tweenty_three,
        R.drawable.facts_tweenty_four,
        R.drawable.facts_tweenty_five,
        R.drawable.facts_tweenty_six,
        R.drawable.facts_tweenty_seven,
        R.drawable.facts_tweenty_eight,
        R.drawable.facts_tweenty_nine,
        R.drawable.facts_thirty,
        R.drawable.facts_thirty_one,
        R.drawable.facts_thirty_two,
        R.drawable.facts_thirty_three,
        R.drawable.facts_thirty_four,
        R.drawable.facts_thirty_five,
        R.drawable.facts_thirty_six,
        R.drawable.facts_thirty_seven,
        R.drawable.facts_thirty_eight,
        R.drawable.facts_thirty_nine,
        R.drawable.facts_forty,
        R.drawable.facts_forty_one,
        R.drawable.facts_forty_two,
        R.drawable.facts_forty_three,
        R.drawable.facts_forty_four,
        R.drawable.facts_forty_five,
        R.drawable.facts_forty_six,
        R.drawable.facts_forty_seven,
        R.drawable.facts_forty_eight,
        R.drawable.facts_forty_nine,
        R.drawable.facts_fifty,
        R.drawable.facts_fifty_one,
        R.drawable.facts_fifty_two,
        R.drawable.facts_fifty_three,
        R.drawable.facts_fifty_four,
        R.drawable.facts_fifty_five,
        R.drawable.facts_fifty_six,
        R.drawable.facts_fifty_seven,
        R.drawable.facts_fifty_eight,

        )

    fun chooseList(currentFact: Int?, nextFact: Int?) {

        var Title = mTitle[currentFact!!]
        var Description = mDescription[currentFact]
        var Image = images[currentFact]
        var NextTitle = mTitle[nextFact!!]
        mainActivity2.getFactsContent(Image, Title, Description, NextTitle)

    }


}